[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "telebeacon"
version = "1.0.0"
description = "Minimal helper package for sending Telegram notifications from Python code."
readme = "README.md"
license = "MIT"
authors = [
    { name = "SneachChea" }
]
requires-python=">=3.11, <4"
dependencies = [
    "requests",
]

[project.optional-dependencies]
dev = [
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-q"
